apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-lb-controller
  labels:
    k8s-app: kubernetes-lb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-lb-controller 
subjects:
- kind: ServiceAccount
  name: kubernetes-lb-controller
  namespace: kube-system
